services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bootoolz-container      
    volumes:
      - ./:/workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - vps
    tty: true   # Keeps the container running in interactive mode
    stdin_open: true

networks:
  vps:
    driver: bridge