services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bootoolz-container 
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"   
      GRADLE_OPTS: "-Xmx512m -Xms512m"   
    volumes:
      - ./:/workspace
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - vps
    tty: true   # Keeps the container running in interactive mode
    stdin_open: true

networks:
  vps:
    driver: bridge